### ISSUE TITLE
Post actions positioning

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/joomjunk#13]
The post actions element is not pushed to the bottom of the message container when there's too much whitespace. Using an absolute positioning fixes this, however then causes overlapping with the quickreply and signature elements.

Trying to avoid using JS to do all of this.

Temporarily commented this functionality out until V2

**Comment by wilsonge** [comment]
Is this the stuff in custom.js (and is all of that your code or is that the code that ships with Kunena?)

**Comment by C-Lodder** [comment]
It's my code but I will come back to this one, so leave it
