### ISSUE TITLE
Change colour of "danger" buttons to JJ red

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/joomjunk#8]

**Comment by wilsonge** [comment]
You may as well wait until we move shit into the less file

**Comment by C-Lodder** [comment]
That was my intention

**Comment by wilsonge** [comment]
Thinking about this might be a good idea to make this template wide rather than forum specific?

**Comment by C-Lodder** [comment]
Nah leave it as it is.

**Comment by wilsonge** [comment]
Fixed and also tweaked the blue primary button whilst I was at it

**Comment by C-Lodder** [comment]
Look much nicer, however could you do this for the whole site and not just the forum?
So add the following to our actual site template less fike:

`.uk-button-primary {
	background-color: @brand_3;
 }
.uk-button-danger {
	background-color: @brand_1;
 }`

**Comment by wilsonge** [comment]
Look two comments earlier where i suggest this and you say no lmao.

But yes I will :D
